# Generated by Django 2.1.5 on 2019-01-08 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_industry', models.CharField(default='bank', max_length=200)),
                ('asset_type', models.CharField(choices=[('股票|stock', '股票|stock'), ('债券|bond', '债券|bond'), ('指数|index', '指数|index'), ('衍生品|derivative', '衍生品|derivative'), ('商品|commodity', '商品|commodity')], default='股票|stock', max_length=200)),
                ('asset_market', models.CharField(max_length=200)),
                ('asset_country', models.CharField(choices=[('中国内地|China', '中国内地|China'), ('中国香港|Hong Kong', '中国香港|Hong Kong'), ('美国|United States', '美国|United States'), ('欧盟|EU', '欧盟|EU'), ('英国|British', '英国|British')], default='中国内地|China', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Basics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=200)),
                ('type_asset', models.CharField(max_length=200)),
                ('date_published', models.DateTimeField(verbose_name='date published')),
                ('date_last', models.DateTimeField(verbose_name='date last traded')),
            ],
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Bond_derivative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deriv_type', models.CharField(max_length=200)),
                ('deriv_bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Bond')),
            ],
        ),
        migrations.CreateModel(
            name='Cash_tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_db', models.CharField(max_length=200)),
                ('init_date', models.DateTimeField(verbose_name='date initialization')),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Index_derivative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deriv_type', models.CharField(max_length=200)),
                ('deriv_Index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Index')),
            ],
        ),
        migrations.CreateModel(
            name='Multi_asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(max_length=200)),
                ('asset_author', models.CharField(default='rc', max_length=200)),
                ('asset_supervisor', models.CharField(max_length=200)),
                ('asset_client', models.CharField(default='rc', max_length=200)),
                ('asset_date_pub', models.DateTimeField(verbose_name='date published')),
                ('asset_group', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(max_length=200)),
                ('port_type', models.CharField(max_length=200)),
                ('port_author', models.CharField(default='rc', max_length=200)),
                ('port_supervisor', models.CharField(max_length=200)),
                ('port_client', models.CharField(default='rc', max_length=200)),
                ('port_date_pub', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Asset')),
                ('stock_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_derivative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deriv_type', models.CharField(max_length=200)),
                ('deriv_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stra_name', models.CharField(max_length=200)),
                ('stra_type', models.CharField(max_length=200)),
                ('stra_author', models.CharField(max_length=200)),
                ('stra_supervisor', models.CharField(max_length=200)),
                ('stra_client', models.CharField(max_length=200)),
                ('stra_date_pub', models.DateTimeField(verbose_name='date published')),
                ('stra_date_last', models.DateTimeField(verbose_name='last update')),
                ('stra_port1', models.ForeignKey(default='rc_a1', on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='User_ciss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('group_ciss', models.CharField(max_length=200)),
                ('user_date_in', models.DateTimeField(verbose_name='date include')),
                ('user_date_last', models.DateTimeField(verbose_name='date last active')),
                ('user_active', models.BooleanField(default=False)),
                ('user_assett', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Asset')),
                ('user_ciss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.DB')),
                ('user_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Portfolio')),
                ('user_stra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Strategy')),
            ],
        ),
        migrations.AddField(
            model_name='stock_derivative',
            name='deriv_stra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Strategy'),
        ),
        migrations.AddField(
            model_name='stock_derivative',
            name='derive_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Portfolio'),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_stra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Strategy'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='port_stra1',
            field=models.ForeignKey(default='rc_a1', on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Strategy'),
        ),
        migrations.AddField(
            model_name='index_derivative',
            name='deriv_stra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Strategy'),
        ),
        migrations.AddField(
            model_name='index_derivative',
            name='derive_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Portfolio'),
        ),
        migrations.AddField(
            model_name='index',
            name='bench_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Portfolio'),
        ),
        migrations.AddField(
            model_name='index',
            name='bench_stra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Strategy'),
        ),
        migrations.AddField(
            model_name='cash_tool',
            name='bond_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Portfolio'),
        ),
        migrations.AddField(
            model_name='cash_tool',
            name='bond_stra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Strategy'),
        ),
        migrations.AddField(
            model_name='bond_derivative',
            name='deriv_stra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Strategy'),
        ),
        migrations.AddField(
            model_name='bond_derivative',
            name='derive_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Portfolio'),
        ),
        migrations.AddField(
            model_name='bond',
            name='bond_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Portfolio'),
        ),
        migrations.AddField(
            model_name='bond',
            name='bond_stra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciss_exhi.Strategy'),
        ),
    ]
