# Generated by Django 2.1.5 on 2019-01-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciss_exhi', '0004_auto_20190108_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='port_path',
            field=models.CharField(default='D:\\CISS_db\\', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='port_name',
            field=models.CharField(default='port_rc181205_market_value_999 - Copy', max_length=200),
        ),
    ]
