# Generated by Django 2.1.5 on 2019-01-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciss_exhi', '0008_auto_20190114_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='stra_link',
            field=models.CharField(default='stra_abm_rc', max_length=200),
        ),
    ]
