# Generated by Django 2.2.6 on 2019-11-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciss_exhi', '0009_strategy_stra_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='dir_stra_data',
            field=models.CharField(default='.\\data_strategy_x\\ ', max_length=200),
        ),
        migrations.AddField(
            model_name='strategy',
            name='dir_stra_files',
            field=models.CharField(default='.\x0ciles_strategy_x\\ ', max_length=200),
        ),
        migrations.AddField(
            model_name='strategy',
            name='link_stra_data',
            field=models.CharField(default='link to startegy data html', max_length=200),
        ),
        migrations.AddField(
            model_name='strategy',
            name='link_stra_exhi',
            field=models.CharField(default='link to startegy exhibition html', max_length=200),
        ),
        migrations.AddField(
            model_name='strategy',
            name='link_stra_files',
            field=models.CharField(default='link to startegy related html', max_length=200),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='stra_client',
            field=models.CharField(default='cs', max_length=200),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='stra_name',
            field=models.CharField(default='cs_name', max_length=200),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='stra_target',
            field=models.CharField(default='return', max_length=200),
        ),
    ]
