# Generated by Django 2.2.6 on 2019-11-19 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ciss_exhi', '0010_auto_20191119_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='stra_date_begin',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Start'),
        ),
    ]
