# Generated by Django 2.2.6 on 2019-11-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciss_exhi', '0011_strategy_stra_date_begin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='dir_stra_data',
            field=models.CharField(default='G:\\CISS_db\\data_applications\\', max_length=200),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='dir_stra_files',
            field=models.CharField(default='G:\\zd_zxjtzq\\rc_reports_cs\\', max_length=200),
        ),
    ]
