# Generated by Django 3.2.12 on 2022-08-24 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ciss_exhi', '0012_auto_20191122_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='fund_analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='rc', max_length=100)),
                ('code', models.CharField(default='110011.OF', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('port_author', models.CharField(default='rc', max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Start')),
                ('style_fund', models.CharField(default='', max_length=200)),
                ('theme_fund', models.CharField(default='', max_length=200)),
                ('ind_1', models.CharField(default='', max_length=200)),
                ('ind_2', models.CharField(default='', max_length=200)),
                ('ind_3', models.CharField(default='', max_length=200)),
                ('ind_num', models.IntegerField(default=0)),
                ('s_down_market', models.IntegerField(default=0)),
                ('s_flat_market', models.IntegerField(default=0)),
                ('s_up_market', models.IntegerField(default=0)),
                ('abstract_analysis', models.CharField(default='', max_length=20000)),
                ('fund_namager', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'fund_analysis',
            },
        ),
    ]
